#use_frameworks!
source 'https://github.com/Doloreng/LXSZPodSpecsRepo.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '12.1'

target 'LXSZAILiveSDK_Example' do
  pod 'LXSZAILiveSDK', :path => '../'
  #public pod
  pod 'WebViewJavascriptBridge', :git => 'https://github.com/stury/WebViewJavascriptBridge.git', :branch => 'master'
end
